services:
  linux_dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${FULL_IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - "${PWD}/${LOCAL_FOLDER}:/home"